### ISSUE TITLE
TypeError: 'filter' object is not subscriptable

### ISSUE THREAD

**Issue by ch1762** [advboxes/AdvBox#43]
```
ch@adv:~/AdvBox/tutorials$ python mnist_tutorial_fgsm.py
Traceback (most recent call last):
  File "mnist_tutorial_fgsm.py", line 152, in <module>
    main()
  File "mnist_tutorial_fgsm.py", line 76, in main
    channel_axis=1)
  File "../advbox/models/paddle.py", line 103, in __init__
    param_grads)[0][1]
TypeError: 'filter' object is not subscriptable

```

**Comment by ch1762** [comment]
安装环境是（1）Anaconda2 5.2.0 64
（2）pip install tensorflow
（3）pip install keras
（4）pip install paddlepaddle
#import paddle.v2 会出错  直接import paddle就可以了

**Comment by fcqfcq** [comment]
python3 和 python2 filter 返回性质不同 
python2 -》** list**
python3 -》 **一个filter对象**
